name: Docto CI/CD Pipeline

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: Build Archive
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate application-prod.yml
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_PROD_YML }}" > src/main/resources/application-prod.yml

      - name: Build JAR without tests and asciidoctor
        run: ./gradlew build -x test -x asciidoctor

      - name: List jar files
        run: ls -al build/libs/

      - name: Find JAR
        run: find build/libs -name "*.jar"

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: build/libs/*.jar

  deploy:
    needs: build
    name: Deploy to Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          use_existing_version_if_available: true
          application_name: Docto
          environment_name: Docto-env
          version_label: ${{ github.SHA }}
          region: us-east-2
          deployment_package: build/libs/docto-0.0.1-SNAPSHOT.jar
